# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-10 19:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_num', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('status', models.IntegerField(choices=[(0, 'enabled'), (1, 'disabled'), (2, 'paused')])),
            ],
        ),
        migrations.CreateModel(
            name='ChannelType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_name', models.CharField(default='', max_length=200)),
                ('common_name', models.CharField(default='', max_length=200)),
                ('measurement_system', models.IntegerField(choices=[(0, 'imperial'), (1, 'metric')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=50)),
                ('status', models.IntegerField(choices=[(0, 'active'), (1, 'inactive')], default=0)),
                ('last_update', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monitor_time', models.DateTimeField()),
                ('transaction_time', models.DateTimeField()),
                ('value', models.FloatField()),
                ('offset_value', models.FloatField(default=0.0)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.Channel')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=32)),
                ('unit_metric', models.CharField(default='', max_length=32)),
                ('unit_imperial', models.CharField(default='', max_length=32)),
                ('abbrev_metric', models.CharField(default='', max_length=32)),
                ('abbrev_imperial', models.CharField(default='', max_length=32)),
                ('m_to_i_function', models.CharField(default='identity', max_length=32)),
                ('i_to_m_function', models.CharField(default='identity', max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='channeltype',
            name='units',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.Unit'),
        ),
        migrations.AddField(
            model_name='channel',
            name='channel_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.ChannelType'),
        ),
        migrations.AddField(
            model_name='channel',
            name='monitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.Monitor'),
        ),
    ]
