# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 13:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('monitor', '0002_auto_20160421_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lower_threshold', models.FloatField(blank=True, null=True)),
                ('upper_threshold', models.FloatField(blank=True, null=True)),
                ('action', models.IntegerField()),
                ('state', models.IntegerField(default=0)),
                ('contacts', models.ManyToManyField(related_name='rules_rule_contacts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RuleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('eval_func', models.CharField(max_length=100)),
                ('template_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='rule',
            name='rule_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.RuleType'),
        ),
    ]
