# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 17:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('monitor', '0003_auto_20160423_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.IntegerField(default=0)),
                ('alert_time', models.DateTimeField(auto_now_add=True)),
                ('resolved_time', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(db_index=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='channel',
            name='last_reading',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='channel_last_reading', to='monitor.Reading'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='action',
            field=models.IntegerField(choices=[(0, 'send email alert'), (1, ' send text alert'), (2, 'send email and text alert')]),
        ),
        migrations.AddField(
            model_name='alert',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monitor.Channel'),
        ),
        migrations.AddField(
            model_name='alert',
            name='monitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monitor.Monitor'),
        ),
        migrations.AddField(
            model_name='alert',
            name='reading',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='monitor.Reading'),
        ),
        migrations.AddField(
            model_name='alert',
            name='rule',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='monitor.Rule'),
        ),
    ]
