# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_auto_20160423_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='rules',
            field=models.ManyToManyField(blank=True, db_index=True, null=True, to='monitor.Rule'),
        ),
    ]
