# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0006_auto_20160430_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='acknowledged_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
