# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-06 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0007_alert_acknowledged_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
    ]
